export const LOGIN_REQUEST = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_FAILED = "LOGIN_USER_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_USER";
export const LOGOUT_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_USER_FAIL";

export const RESTORE_REQUEST = "RESTORE_REQUEST"
export const RESTORE_SUCCESS = "RESTORE_REQUEST_SUCCESS"
export const RESTORE_FAIL = "RESTORE_REQUEST_FAIL"

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILED = "SEND_OTP_FAIL";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAIL";

export const RESEND_OTP = "RESEND_OTP";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILED = "RESEND_OTP_FAIL";


export const STORE_MOBILE = "STORE_MOBILE";
export const STORE_MOBILE_SUCCESS = "STORE_MOBILE_SUCCESS";
export const STORE_MOBILE_FAILED = "STORE_MOBILE_FAIL";

export const REGISTER_PARENT = "REGISTER_PARENT";
export const REGISTER_PARENT_SUCCESS = "REGISTER_PARENT_SUCCESS";
export const REGISTER_PARENT_FAILED = "REGISTER_PARENT_FAIL";

export const GET_GRADE_DATA = "GET_GRADE_DATA";
export const GET_GRADE_DATA_SUCCESS = "GET_GRADE_DATA_SUCCESS";
export const GET_GRADE_DATA_FAILED = "GET_GRADE_DATA_FAILED";

export const REGISTER_STUDENT = "REGISTER_STUDENT";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAILED = "REGISTER_STUDENT_FAIL";


export const EDIT_STUDENT = "EDIT_STUDENT";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_FAILED = "EDIT_STUDENT_FAILED";

export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILED = "DELETE_STUDENT_FAILED";

