export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const SET_USER_DETAILS = "SET_USER_DETAILS";

export const DASHBOARD = "DASHBOARD";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FALIED = "DASHBOARD_FALIED";

export const DEMO_SLOTS = "DEMO_SLOTS";
export const DEMO_SLOTS_SUCCESS = "DEMO_SLOTS_SUCCESS";
export const DEMO_SLOTS_FAILED = "DEMO_SLOTS_FAILED";

export const SELECT_CURRENT_KID = "SELECT_CURRENT_KID";

export const BOOK_DEMO = "BOOK_DEMO";
export const BOOK_DEMO_SUCCESS = "BOOK_DEMO_SUCCESS";
export const BOOK_DEMO_FAILED = "BOOK_DEMO_FAILED";

export const CANCEL_DEMO = "CANCEL_DEMO";
export const CANCEL_DEMO_SUCCESS = "CANCEL_DEMO_SUCCESS";
export const CANCEL_DEMO_FAILED = "CANCEL_DEMO_FAILED";

export const RESCHEDULE_DEMO = "RESCHEDULE_DEMO";
export const RESCHEDULE_DEMO_SUCCESS = "RESCHEDULE_DEMO_SUCCESS";
export const RESCHEDULE_DEMO_FAILED = "RESCHEDULE_DEMO_FAILED";

export const CANCEL_SLOT = "CANCEL_SLOT";
export const CANCEL_SLOT_SUCCESS = "CANCEL_SLOT_SUCCESS";
export const CANCEL_SLOT_FAILED = "CANCEL_SLOT_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED"; 

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILED = "REMOVE_FROM_CART_FAILED"; 

export const GET_CART_LIST = "GET_CART_LIST";
export const GET_CART_LIST_SUCCESS = "GET_CART_LIST_SUCCESS";
export const GET_CART_LIST_FAILED = "GET_CART_LIST_FAILED";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAILED = "EDIT_ADDRESS_FAILED";

export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const REMOVE_ADDRESS_SUCCESS = "REMOVE_ADDRESS_SUCCESS";
export const REMOVE_ADDRESS_FAILED = "REMOVE_ADDRESS_FAILED";

export const LIST_ADDRESS = "LIST_ADDRESS";
export const LIST_ADDRESS_SUCCESS = "LIST_ADDRESS_SUCCESS";
export const LIST_ADDRESS_FAILED = "LIST_ADDRESS_FAILED";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS ="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const UPDATE_PAYMENT_STATUS = "UPDATE_PAYMENT_STATUS";
export const UPDATE_PAYMENT_STATUS_SUCCESS ="UPDATE_PAYMENT_STATUS_SUCCESS";
export const UPDATE_PAYMENT_STATUS_FAILED = "UPDATE_PAYMENT_STATUS_FAILED";

export const VIEW_CURRICULAM = "VIEW_CURRICULAM";
export const VIEW_CURRICULAM_SUCCESS = "VIEW_CURRICULAM_SUCCESS";
export const VIEW_CURRICULAM_FAILED = "VIEW_CURRICULAM_FAILED";

export const BOOK_LIVE_CLASS = "BOOK_LIVE_CLASS";
export const BOOK_LIVE_CLASS_SUCCESS = "BOOK_LIVE_CLASS_SUCCESS";
export const BOOK_LIVE_CLASS_FAILED = "BOOK_LIVE_CLASS_FAILED";

export const SUBSCRIPTION_DETAILS = "SUBSCRIPTION_DETAILS";
export const SUBSCRIPTION_DETAILS_SUCCESS = "SUBSCRIPTION_DETAILS_SUCCESS";
export const SUBSCRIPTION_DETAILS_FAILED = "SUBSCRIPTION_DETAILS_FAILED";

export const BATCH_DETAILS = "BATCH_DETAILS";
export const BATCH_DETAILS_SUCCESS = "BATCH_DETAILS_SUCCESS";
export const BATCH_DETAILS_FAILED = "BATCH_DETAILS_FAILED";

export const STUDENT_CLASSES = "STUDENT_CLASSES";
export const STUDENT_CLASSES_SUCCESS = "STUDENT_CLASSES_SUCCESS";
export const STUDENT_CLASSES_FAILED = "STUDENT_CLASSES_FAILED";

export const STUDENT_CATEGORY_CLASSES = "STUDENT_CATEGORY_CLASSES";
export const STUDENT_CATEGORY_CLASSES_SUCCESS = "STUDENT_CATEGORY_CLASSES_SUCCESS";
export const STUDENT_CATEGORY_CLASSES_FAILED = "STUDENT_CATEGORY_CLASSES_FAILED";

export const APPLY_COUPON = "APPLY_COUPON";
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_FAILED = "APPLY_COUPON_FAILED";

export const REMOVE_COUPON = "REMOVE_COUPON";
export const REMOVE_COUPON_SUCCESS = "REMOVE_COUPON_SUCCESS";
export const REMOVE_COUPON_FAILED = "REMOVE_COUPON_FAILED";

export const STUDENT_REPORT = "STUDENT_REPORT";
export const STUDENT_REPORT_SUCCESS = "STUDENT_REPORT_SUCCESS";
export const STUDENT_REPORT_FAILED = "STUDENT_REPORT_FAILED";

export const STUDENT_ACTIVITY = "STUDENT_ACTIVITY";
export const STUDENT_ACTIVITY_SUCCESS = "STUDENT_ACTIVITY_SUCCESS";
export const STUDENT_ACTIVITY_FAILED = "STUDENT_ACTIVITY_FAILED";

export const DEMO_RESULT = "DEMO_RESULT";
export const DEMO_RESULT_SUCCESS = "DEMO_RESULT_SUCCESS";
export const DEMO_RESULT_FAILED = "DEMO_RESULT_FAILED";

export const PARENT_FEEDBACK = "PARENT_FEEDBACK";
export const PARENT_FEEDBACK_SUCCESS = "PARENT_FEEDBACK_SUCCESS";
export const PARENT_FEEDBACK_FAILED = "PARENT_FEEDBACK_FAILED";


export const DEVICE_INFO = "DEVICE_INFO";
export const DEVICE_INFO_SUCCESS = "DEVICE_INFO_SUCCESS";
export const DEVICE_INFO_FAILED = "DEVICE_INFO_FAILED";

export const UPCOMING_CLASSES = "UPCOMING_CLASSES";
export const UPCOMING_CLASSES_SUCCESS = "UPCOMING_CLASSES_SUCCESS";
export const UPCOMING_CLASSES_FAILED = "UPCOMING_CLASSES_FAILED";

export const WORKBOOK_UPLOAD = "WORKBOOK_UPLOAD";
export const WORKBOOK_UPLOAD_SUCCESS = "WORKBOOK_UPLOAD_SUCCESS";
export const WORKBOOK_UPLOAD_FAILED = "WORKBOOK_UPLOAD_FAILED";

export const CLASS_CANCEL ="CLASS_CANCEL";
export const CLASS_CANCEL_SUCCESS ="CLASS_CANCEL_SUCCESS";
export const CLASS_CANCEL_FAILED ="CLASS_CANCEL_FAILED";

export const STAR_BADGE_REPORT = "STAR_BADGE_REPORT";
export const STAR_BADGE_REPORT_SUCCESS = "STAR_BADGE_REPORT_SUCCESS";
export const STAR_BADGE_REPORT_FAILED = "STAR_BADGE_REPORT_FAILED";

export const RATING_TAGS = "RATING_TAGS";
export const RATING_TAGS_SUCCESS = "RATING_TAGS_SUCCESS";
export const RATING_TAGS_FAILED = "RATING_TAGS_FAILED";

export const SUBMIT_TEACHER_RATING = "SUBMIT_TEACHER_RATING";
export const SUBMIT_TEACHER_RATING_SUCCESS = "SUBMIT_TEACHER_RATING_SUCCESS";
export const SUBMIT_TEACHER_RATING_FAILED = "SUBMIT_TEACHER_RATING_FAILED";

export const TEACHER_RATING = "TEACHER_RATING";
export const TEACHER_RATING_SUCCESS = "TEACHER_RATING_SUCCESS";
export const TEACHER_RATING_FAILED = "TEACHER_RATING_FAILED";